### ISSUE TITLE
GZ Doom 4.11?

### ISSUE THREAD

**Issue by TClark1011** [luxtorpeda-dev/packages#1043]
### Project Link

https://zdoom.org/downloads

### Project License

?

### Steam App Ids

?

### Additional Context

Sorry if this is not the place for this, or if it's been asked before, but I couldn't figure out where else I could ask this. I was just wondering what's going on with support for GZDoom 4.11? It looks like support was added, but then reverted in this commit https://github.com/luxtorpeda-dev/packages/commit/29d97adc7710940ac206575be7464eaebc43c77b. I was just wondering if support for GZDoom 4.11 will be added back in, or if not is there a way for me to manually update my installation of GZDoom to the newer version?

**Comment by d10sfan** [comment]
Gzdoom is being held back (same as raze) because of a bug in the engine related to mesa drivers. What happens is a memory leak that tries to eat up the entire system's memory.

You can see more information here: https://github.com/ZDoom/Raze/issues/966

Because of that, I don't feel comfortable with updating the versions of these two until they fix the issue. I've added some additional details to the metadata to make it a bit clearer why it's being held back.

Whenever they fix that upstream, I can update to the latest. Let me know if you need anything!

**Comment by TClark1011** [comment]
Okay, that makes sense. For now, is it possible for me to update my installation to 4.11 manually?

**Comment by d10sfan** [comment]
I believe so, you can enable the hash check mode, which'll disable luxtorpeda from extracting until there's a new update from my side.

**Comment by TClark1011** [comment]
Okay, I just checked my `config.json` file and that was already on. When I go to install GZDoom I can see there are few different versions for different linux setups, which one should I use? Sorry for bothering you, I'm just not very familiar with linux. I should probably also mention I'm running it on a steam deck.

**Comment by d10sfan** [comment]
I'm not sure what you mean on the install gzdoom part, but you could try flatpaks or the linux portable on the gzdoom github. Note that you'll most likely run into the same memory leak issue (it's not from luxtorpeda, it's an upstream problem).

**Comment by Lexicon102** [comment]
@d10sfan It seems GZ Doom has been fixed, any plans to implement the newest updates?
