### ISSUE TITLE
Marathon - Aleph One

### ISSUE THREAD

**Issue by HellsBells24** [luxtorpeda-dev/packages#1206]
### Project Link

https://alephone.lhowon.org/

### Project License

Aleph One is available under the terms of the GNU General Public License (GPL)

### Steam App Ids

https://steamdb.info/app/2398450/
https://steamdb.info/app/2398490/
https://steamdb.info/app/2398520/

### Additional Context

Looks like the Aleph One versions of the Marathon games have come to Steam. Does that mean it can be incorporated into Luxtorpeda?

**Comment by d10sfan** [comment]
Thanks for the request, I'm working on it with this PR: https://github.com/luxtorpeda-dev/packages/pull/1207

The other two games haven't released yet, when they do I'll plan on updating and feel free to update this ticket or create a new one when those release, as a reminder, since I may miss the release of those.

**Comment by d10sfan** [comment]
It's been added, it should be live shortly.
