### ISSUE TITLE
ironwail does not have QuakeWorld hud

### ISSUE THREAD

**Issue by rehtlaw** [luxtorpeda-dev/packages#1320]
### Game

Quake

### Engine

ironwail

### Linux Distribution

EndeavourOS

### Luxtorpeda Version

70.1.1

### Bug description

running the version of ironwail that comes with luxtorpeda, I only have access to the `Classic`, `Modern 1`, and `Modern 2` HUDs, with the `QuakeWorld` HUD missing from the selection. Downloading the last version of ironwail from https://github.com/andrei-drexler/ironwail/releases and running it, I have access to all 4 HUDs in the options.

### Steps To Reproduce

1. run Quake and select ironwail (I've tested both the regular and re-release version)
2. click on options and check the available HUDs

### Expected Behavior

Classic, QuakeWorld, Modern 1 and Modern 2 being the available HUD options

### Additional Context

I tried to replace the `ironwail` executable with the upstream one, but it just started to crash whenever I ran it through steam with a 127 error code(directly running the .sh scripts seemed to work just fine?).

**Comment by d10sfan** [comment]
That's mainly because ironwail hasn't done a release in a while. QuakeWorld Hud from what I can tell was added in https://github.com/andrei-drexler/ironwail/commit/43648647d5d8418f0050107df504a685d5256bd9, which is newer than their most recent release (https://github.com/andrei-drexler/ironwail/releases/tag/v0.7.0).

Once they've created a new release, this and the other features will be available.
