### ISSUE TITLE
Serious Sam 2

### ISSUE THREAD

**Issue by ShFil119** [luxtorpeda-dev/packages#172]
* Project link: https://ftp.jeuxlinux.fr/files/ss_linuxbeta_rc_2_1_public.tar.gz
* Project license: Unknown
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: NO
* Is source code stored in Git?: NO
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/204340/
    
This looks like official beta:
steamcommunity.com/app/204340/discussions/0/846945579838435691/#c846946775252238771
https://web.archive.org/web/20091224225932/http://files.seriouszone.com/catdisplay.php?catid=111
https://www.pc-erfahrung.de/software/spiele-artikel-loesu/serious-sam-ii-windows-linux.html

**Comment by rea987** [comment]
My native SS2 installation guide;

https://www.reddit.com/r/linux_gaming/comments/7a2o1d/guide_serious_sam_2_native_installation/

Note that, SS2 has been updated heavily since its Windows version's release on Windows. Currently Linux version is outdated and since the closure of GameSpy, it cannot play online even with Linux versions. Therefore, it's better to keep players informed beforehand.

**Comment by d10sfan** [comment]
@rea987 @ShFil119 I looked over the documentation and the game works fine but I'm unable to hear any sound. Are you all able to hear sound if  you try these steps? I used the linked guide that rea987 linked.

**Comment by d10sfan** [comment]
I was able to do a workaround by copying SfxOAL.so to SfxDSD.so and that caused the sound to work.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/189
