### ISSUE TITLE
Unreal Gold

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#192]
* Project link: *https://www.oldunreal.com/oldunrealpatches.html*
* Project license: *Proprietary with NDA*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/13250/

## Additional information

This is Linux native release of Unreal Gold that features **Unreal** and **Unreal: Return to Na Pali**. The port uses SDL2 and PulseAudio compatible audio, hence doesn't require PADSP and SDLCL. The installer is an .exe that requires WINE to install to Linux native libraries. Additional Linux native libraries are stored in ../Help/lin_convenience_libs.tar.bz2

**Comment by d10sfan** [comment]
For me, this one works except for I get a crash with Audio:

Processors / Cores 8
Forcing CPU affinity disabled.
OpenAL: Failed, trying (again) default device
OpenAL: EFX Extensions found
Segmentation fault (core dumped)

I tried their FAQ (https://www.oldunreal.com/wiki/index.php?title=Oldunreal_227_Linux_FAQ#Unreal_segfaults_at_startup) which said to set ProbeDevicesOnly=True, but then I had no sound. This is after using the convenience libs. 

Have you been able to hear audio on this one? If so, what were the steps you needed to run it?

An issue of this one is the requirement of Wine. I'd like to be able to support flatpak environments and environments that do not have packages installed like wine. Because of that, I could compile and provide wine, but would have to see if that's feasible.

**Comment by rea987** [comment]
Extracting _lin_convenience_libs.tar.bz2_ helped to be able to run the game and have sound. However, the game still doesn't play music. Considering that one of the most important aspect of Unreal Gold is the music, that needs to be sorted out. Will investigate further in the upcoming weeks.

I believe Linux libraries can just be pre-extracted to use it additionally without needing WINE.

**Comment by d10sfan** [comment]
Ok, let me know what you find in terms of the sound and music.

The Wine part is mostly related to the exe itself that has the binaries. If there's some way of extracting it without having to use wine, then that would be great.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/216

This one takes a bit to setup, mostly because the binaries themselves need to be downloaded manually, as doing that automatically did not work with the website, as well as Wine needing to be installed on the host system. Then the installer needs to be run through Wine. 

The music and sound work, and once this initial installation portion is over, it launches like normal. 

A readme can be found here: https://github.com/luxtorpeda-dev/packages/blob/master/engines/unreal-gold/assets/README.txt

Of course, let me know if anyone has ideas to streamline this one. Feel free to comment here or create a new ticket/PR.

**Comment by rea987** [comment]
I suspect Oldunreal's 227 Patch for Unreal Gold uses SDL1.2 as the game doesn't support `Alt+Tab` or Steam Overlay via `Shift+Tab` on Mint 19.3. Can **SDLCL** applied in order have such functions? Thank you!

**Comment by d10sfan** [comment]
> I suspect Oldunreal's 227 Patch for Unreal Gold uses SDL1.2 as the game doesn't support `Alt+Tab` or Steam Overlay via `Shift+Tab` on Mint 19.3. Can **SDLCL** applied in order have such functions? Thank you!

I can look into that. I'll let you know once I've had a chance to look at that for SDLCL.

Having the steam overlay crashed the game, so it's purposely disabled. I'm not sure if SDLCL will help with that, but I'll try that.

**Comment by rea987** [comment]
> Having the steam overlay crashed the game, so it's purposely disabled. I'm not sure if SDLCL will help with that, but I'll try that.

Steam Overlay is not a must but native Alt+Tab would be a great improvement. Thank you!

**Comment by d10sfan** [comment]
SDLCL has been added in this PR: https://github.com/luxtorpeda-dev/packages/pull/224

Note that steam overlay still does not work. Enabling it causing the game to crash.
