### ISSUE TITLE
Natural Selection 2

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#218]
* Project link: https://store.steampowered.com/app/4920/Natural_Selection_2/
* Project license: *Proprietary*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/4920/

## Additional information

Natural Selection 2 is an Aliens vs Marines themed FPS/RTS game. Its Linux support was dropped in 2019;

https://unknownworlds.com/ns2/a-note-to-our-linux-users/

Later on, due to user request developer put an obsolete [Linux] branch for those want to play outdated version.

https://steamcommunity.com/app/4920/discussions/0/2692512878719460182/?tscn=1568973412#c1628538005512564029

It looks like recent launch config update has broken the Linux launch option that looks for ns2.exe.

https://steamcommunity.com/app/4920/discussions/1/2994296961836681550/
https://steamdb.info/app/4920/history/?changeid=10234342	

I wonder if Luxtorpeda utilized to launch the outdated Linux version?

**Comment by d10sfan** [comment]
The way Luxtorpeda interacts with Steam is by setting itself up as a compatibility tool. Because of that, it downloads whatever the Windows branch of the game is.

Because of that, unless Natural Selection 2 provides the Linux binaries in the Windows depot as well, then luxtorpeda wont work for it. You might be able to do something to make it work by changing the Steam launch options to point it in the right direction.

**Comment by d10sfan** [comment]
Please feel free to comment if there's something else you feel luxtorpeda can do here. Closing for now.
