### ISSUE TITLE
Strife Community Edition

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#309]
* Project link: *https://strife-ce.com/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/strife-ce/strife-ce-client
https://github.com/strife-ce/strife-ce-datamodel

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/339280/

## Additional information

https://www.reddit.com/r/linux_gaming/comments/julkrb/strife_community_edition_revives_the_dead_moba/

**Comment by d10sfan** [comment]
It looks like this one may not be possible with luxtorpeda, because this client is looking for the existing Linux binaries.

Since luxtorpeda is a compatibility tool like Proton, when you switch to it, it downloads the Windows binaries and the client is unable to load.

Let me know if you have any ideas to support this one.
