### ISSUE TITLE
MINERVA: Metastasis map error

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#315]
**metastasis_4a map is broken**
metastasis_4a is a peculiar map that the player starts the map in laying facing up position, then the player gets up.

https://youtu.be/Fh9rCYufAbk?t=2030

In Luxtorpeda version of the game, the player starts the map in facing down position and cannot move.

![resim](https://user-images.githubusercontent.com/1547646/112769818-d8c95a00-902b-11eb-8e22-a51936cb466a.png)

With a clean HL2:EP1, Source SDK Base 2013 SP, Minerva installation; mod version can run the map properly;

https://steamcommunity.com/sharedfiles/filedetails/?id=754991349

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the game
2. Enter map command: `map metastasis_4a`
3. See whether the player starts facing down or up.

**Expected behaviour**
Player starts in facing up position and able to get up.

**Additional context**
I suspect that's a **gameinfo.txt** issue. Big Mac's gameinfo.txt file works fine with mod version. I wonder whether it is used.

https://pastebin.com/7htcfkZP

**Comment by d10sfan** [comment]
If you leave the game as is ,other than overwriting the gameinfo.txt you mentioned, does it then work?

This would require manually editing the cached download and changing the one in the archive. If that fixes it, I can then make that change.

This is the gameinfo.txt that is used: https://github.com/luxtorpeda-dev/packages/blob/master/engines/source-sdk-2013/assets/metastasis/gameinfo.txt This is also the start of the game, to show what commands are run: https://github.com/luxtorpeda-dev/packages/blob/master/engines/source-sdk-2013/assets/metastasis/run-metastasis.sh

You can see if there's any differences that stand out to you.

**Comment by d10sfan** [comment]
This should be fixed now with this commit: https://github.com/luxtorpeda-dev/packages/commit/efc94dac9b50b6b443a4ce5158be1c4d49c2d58b

It looks like the issues was the ep2 parts were overriding some data, I got the idea to change the gameinfo this way because of this thread: https://duckytopia.wordpress.com/tutorials/gordon-wakes-up/

I was able to successfully see the chapter 4 intro the way it looks like it's supposed to be. Let me know if you have any further issues.
