### ISSUE TITLE
idTech Games

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#424]
### Project Link

Various

### Project License

GPL

## id Tech Games:
- [Strife: Veteran Edition](https://steamdb.info/app/317040/)
- [Hexen II Demo](https://steamdb.info/app/9120/)
- [Quake II RTX](https://steamdb.info/app/1089130/)
- [Quake III Arena Demo](https://steamdb.info/app/9080/)
- [Quake III: Team Arena Demo](https://steamdb.info/app/9090/)
- [Quake Live](https://steamdb.info/app/282440/)
- [Quake Live Testing](https://steamdb.info/app/344320/)
- [DOOMBRINGER](https://steamdb.info/app/1156120/)
- [DOOMBRINGER Deathmatch Demo](https://steamdb.info/app/1576690/)
- [Hedon Demo](https://steamdb.info/app/1393720/)
- [Iron Grip: Warlord](https://steamdb.info/app/31700/)
- [Iron Grip: Warlord - Demo](https://steamdb.info/app/31710/)
- [SharpShooter3D](https://steamdb.info/app/873150/)
- [Steel Storm: Burning Retribution](https://steamdb.info/app/96200/)
- [Steel Storm: Burning Retribution Demo](https://steamdb.info/app/201090/)
- [Project Absentia Demo](https://steamdb.info/app/1679920/)
- [Relentless Frontier Demo](https://steamdb.info/app/1731320/)
- [The Forgotten Sprites](https://steamdb.info/app/809400/)
- [Retroninjacyberassassin](https://steamdb.info/app/1566570)
- [THE FANGS HUNTRESS](https://steamdb.info/app/1624460/)
- [battleMETAL](https://steamdb.info/app/1447830/)
- [Dismantled](https://steamdb.info/app/1458810/)
- [Steel Storm: A.M.M.O.](https://steamdb.info/app/251790/)
- [The Wastes](https://steamdb.info/app/793670/)
- [Warfork](https://steamdb.info/app/671610/)
- [Vomitoreum](https://steamdb.info/app/1549750/)
- [DOOM 3 Demo](https://steamdb.info/app/9100/)

### Additional Context

This issue serves to document some of the remaining idTech games and demos I could find on SteamDB that might have flown under the radar. I trust your judgement on how (or if) these games are supported.

**Comment by rea987** [comment]
- Strife: Veteran Edition: Has a native Linux version on Steam.
- Quake II RTX: Has a native Linux version on Steam.
- Quake Live & Testing: I doubt whether it works with ioquake3 due to being closed source.
- DOOMBRINGER & Demo: Have native Linux versions on Steam.
- Hedon Demo: Has a native Linux version on Steam.
- Steel Storm: Burning Retribution & Demo: Have native Linux versions on Steam.
- Steel Storm: A.M.M.O.: Seems to be delisted and abandoned.
- The Wastes: Has a native Linux version on Steam.
- Warfork: Has a native Linux version on Steam.
- Vomitoreum: Has a native Linux version on Steam.
- DOOM 3 Demo: Suggested previously, @d10sfan was unable to install it. Removing its license from, then readding would work. https://store.steampowered.com/account/licenses/

**Comment by d10sfan** [comment]
@JoshuaFern For the ones with native versions, not sure if there's a benefit to building

There's many in here that appear to be closed source, so for those, if you find any projects that build them, let me know. Otherwise, if you could order these by engine used and ones that have a project behind them.

**Comment by d10sfan** [comment]
So far at a glance, looks like the following look promising:

* https://store.steampowered.com/app/1447830/battleMETAL/ - seems to need normal darkplaces, there's a repo (https://github.com/Subject9x/battleMETAL) but seems to only be quakec client code. If anyone owns this one, let me know and I could put out a test build, or if someone doesn't mind gifting it.
* https://store.steampowered.com/app/1624460/THE_FANGS_HUNTRESS - this one looks like a wolf engine game, but not 100% sure
* https://store.steampowered.com/app/1566570/Retroninjacyberassassin - looks like a doom mod?
* https://store.steampowered.com/app/1662010/Project_Absentia/ - looks to work with gzdoom or their own fork of it
* https://store.steampowered.com/app/1677900/Relentless_Frontier/ - another gzdoom game

Normally, unless there's a benefit to building for an already native game (better source port or the game not being updated), then I'd prefer to hold off on those. Also, delisted games are alot harder to mess with, since unless someone owns them, they are very difficult to test.

**Comment by JoshuaFern** [comment]
- [Strife: Veteran Edition](https://steamdb.info/app/317040/) - This game runs on the proprietary Kex engine like Quake 2021, but it includes the original DOS release in the depot and should be easy to support with the existing GZDoom. There's also this open source release that seems to be based on Chocolate Doom. https://github.com/svkaiser/strife-ve
- [Retroninjacyberassassin](https://steamdb.info/app/1566570) - Seems to ship with zandronum, there's a `zandronum.pk3` and running `strings Retroninjacyberassassin.exe | grep zandronum` reveals a lot of zandronum strings.

**Comment by d10sfan** [comment]
@JoshuaFern I've added Strife to the "promising" list, I don't own the game currently though. Also, updated the info for retro...

Thanks

**Comment by d10sfan** [comment]
@JoshuaFern Strife VE has been added, currently just the veteran edition supported.

**Comment by d10sfan** [comment]
@JoshuaFern @rea987 

For the demos, I haven't had any success downloading demos after I own the base game. If you all are able to launch the demos, then a pull request would be welcome for implementation of these. Or if you can provide the necessary information for commands that should be run and are able to test.

**Comment by d10sfan** [comment]
@JoshuaFern It looks like https://store.steampowered.com/app/1447830/battleMETAL/ is planning on adding native support in the future, so will hold off for now.

**Comment by rea987** [comment]
> @JoshuaFern @rea987
> 
> For the demos, I haven't had any success downloading demos after I own the base game. If you all are able to launch the demos, then a pull request would be welcome for implementation of these. Or if you can provide the necessary information for commands that should be run and are able to test.

I link this as a reference;

https://github.com/luxtorpeda-dev/packages/issues/360

I have just downloaded Doom 3 Demo on Steam successfully. I also happened to purchased Doom 3 and Doom 3: Resurrection of Evil in August 2021; according to my Steam licenses history, I added Doom 3 Demo in my account in May 2021.

https://steamcommunity.com/id/realtunya/games/?tab=all

Running Doom 3 Demo via dhewm 3 is quite straightforward;

- Launch console enable Steam client: `steam -console`
- Download Doom 3 Demo via Steam Console: `app_install 9100`
- Copy `~/.local/share/Steam/steamapps/common/Doom 3 Demo/demo` folder into dhewm3 directory.
- Launch dhewm 3: `./dhewm3`

![Ekran Görüntüsü 2021-09-14 10-27-59](https://user-images.githubusercontent.com/1547646/133215686-bd7e5707-ac24-4bc8-8120-16bf1f7d672f.png)
![Ekran Görüntüsü 2021-09-14 10-29-41](https://user-images.githubusercontent.com/1547646/133215742-6aec60d1-813b-4cf2-84
![shot00001](https://user-images.githubusercontent.com/1547646/133215920-6e7f35f0-bdb1-4b13-ad85-6434179123ac.png)
![shot00002](https://user-images.githubusercontent.com/1547646/133216003-52d2ff2b-a939-427c-982f-bac1d1d9b6a7.png)
86-b84d9ff19f67.png)

For not being able to download demos after buying full game; would removing demos license from Steam account then re-adding work? Licenses page has license remove option for demos and free games;

https://store.steampowered.com/account/licenses/

**Comment by d10sfan** [comment]
@rea987 @JoshuaFern With this method, was able to get the following demos to work:

* Doom 3 Demo - https://github.com/luxtorpeda-dev/packages/commit/25998630e33cc28b44208d9f17d9363d13bd6a4c
* Quake III Arena Demo - https://github.com/luxtorpeda-dev/packages/commit/891b1e1160d745e1bf37ae6d1d0151d3ac699414

The following demos would not download no matter what I did, if you're able to get them to work, then a pull request would be welcome:

* Hexen II Demo

Quake III Team Arena Demo would not load properly, looks like because ioquake3 is expecting the base game pack which this demo does not have.

**Comment by d10sfan** [comment]
@rea987 @JoshuaFern 

I've also added zandronum (https://github.com/luxtorpeda-dev/packages/commit/8bdd8f3d37426f312d54858f45b20e308e9369d0), using the upstream provided download for https://store.steampowered.com/app/1566570/Retroninjacyberassassin so that should close out the ones possible here.

Thanks for the suggestions and help with getting the demos to work. Let me know if I missed any in here that are doable.

**Comment by JoshuaFern** [comment]
I've tested Retroninjacyberassassin and Strife, both seem to be working great. Although Retroninja is a terrible game.
I think it could be useful to add Zandronum as an option for other DOOM engine games as well.

I was able to download the Hexen II Demo by launching Steam with `steam -console` and running `app_install 9120` in the Steam console. It doesn't run for me with Proton.

**Comment by d10sfan** [comment]
@JoshuaFern For Hexen II demo, I was unable to run it with that, so if you're able to run it and you can get it to work with the engine, feel free to create a pull request for it.

**Comment by rea987** [comment]
> @JoshuaFern For Hexen II demo, I was unable to install it with that, so if you're able to install it and you can get it to work with the engine, feel free to create a pull request for it.

- As I checked my Steam licensed, I purchased Heretic/Hexen Pack in November 2017 whereas I added Hexen II Demo to my account in August 2017.
- As it is an outdated id Tech 2 game, it requires one of following launch commands to launch properly with Proton:

`MESA_EXTENSION_MAX_YEAR=2003 %command% -window -width 1280 -height 800 -bpp 32`
`PROTON_OLD_GL_STRING=1 %command% -window -width 1280 -height 800 -bpp 32`

- Similar to Doom 3 Demo, steps I followed; `steam -console` > `app_license_request 9120` (if you don't have it) > `app_install 9120`
- Unlike most other source ports, Hammer of Thyrion packaged demo versions with the port. `hexen2demo_nov1997-linux-x86_64.tgz` (November 1997 demo) is identical with the demo version on Steam. So, it would be simple overwrite command to download and launch Linux demo.

http://uhexen2.sourceforge.net/download.html#linux_demo
http://sourceforge.net/project/downloading.php?group_id=124987&filename=hexen2demo_nov1997-linux-x86_64.tgz
