### ISSUE TITLE
Source Engine enhancements

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#557]
In this bug report/feature request I would like to touch upon 2 issues;

1) Resistance Element returns following error even if **Source SDK Base 2013 Singleplayer** and **Half-Life 2: Episode One** are installed already:

`Unable to load surface prop file 'scripts/surfaceproperties_ep2.txt' (referenced by manifest file 'scripts/surfaceproperties_manifest.txt')`
 
![Ekran Görüntüsü 2021-11-01 21-03-20](https://user-images.githubusercontent.com/1547646/139730009-c525b705-3a4c-4a01-8729-3373adfa2596.png)

Installing **Half-Life 2: Episode Two** fixes the issue. Can HL2:EP1 replaced by HL2:EP2 in Resistance Element Luxtorpeda script?

2) As I mentioned HL2: DownFall package request, HL2 has recently been updated with beta branch which offers up to 110 degree FOV and optional Vulkan renderer.

https://github.com/luxtorpeda-dev/packages/issues/554

In that regard, can Luxtorpeda offer option to choose between Source SDK 2013 and HL2:EP2 for HL2 mods on Steam? Those are;

- Entropy : Zero : https://steamdb.info/app/714070/
- Half-Life 2: DownFall : https://steamdb.info/app/587650/
- Half-Life 2: Year Long Alarm : https://steamdb.info/app/747250/

**Comment by d10sfan** [comment]
@rea987 

I was unable to get the hl2 episode 2 version of downfall to work. If you can provide a pr for that, feel free.

I believe that not all of the games here would work with hl2, there have been issues with using the wrong client before, with scripting errors and the like. If you're able to show that using hl2 instead of the source sdk works, then please provide gameinfos and any other necessary information.

**Comment by d10sfan** [comment]
@rea987 

https://github.com/luxtorpeda-dev/packages/commit/f24d94df4ee3133aea29109cdb167cab4f48550b should fix it where ep2 is required, instead of ep1.

**Comment by rea987** [comment]
To avoid HL2, HL2:EP1, HL2:EP2 and Source SDK 2013 interfering with each other, I deleted all of them, cleared their directories then reinstalled fresh HL2:EP2. I was able to run **Half-Life 2: DownFall** and **Half-Life 2: Year Long Alarm** as a HL2:EP2 mod by editing gameinfo.txt.

- Half-Life 2: DownFall:
https://gist.github.com/rea987/c4dad7cebc12c1a9701a5cb3d1e68fb1

- Half-Life 2: Year Long Alarm:
https://gist.github.com/rea987/f9428dfba5339943df273230917ab36f

However, I was unable to do the same with **Entropy : Zero**; considering that the port uses compiled binaries from z33ky project project, it's expected.

**Comment by d10sfan** [comment]
@rea987 thanks I'll take a look when I have a chance

**Comment by d10sfan** [comment]
@rea987 

I was unable to get that to work with those two games to use hl2 instead of the source sdk 2013. This is most likely because your test is about getting them to run as sourcemods, when the scripts are trying to launch them from a steam game.

The scripts for each game are here: https://github.com/luxtorpeda-dev/packages/tree/master/engines/source-sdk-2013/assets

If you're able to make changes to those that get this to work, let me know.
