### ISSUE TITLE
Soldat 

### ISSUE THREAD

**Issue by jesperjackson** [luxtorpeda-dev/packages#582]
### Project Link

https://github.com/Soldat/soldat/

### Project License

MIT

### Steam App Ids

- https://steamdb.info/app/638490/

### Additional Context
Official engine source code. Links to additional information:

- https://steamcommunity.com/games/638490/announcements/detail/2192636057421436703 - contains information on differences from Steam version.
- https://github.com/Soldat/soldat/wiki/A-beginner's-guide-to-Soldat-development - contains information on compiling with Steam integration.

**Comment by d10sfan** [comment]
@ToughGuyKunio 

There's a few possible issues here:

* Steam integration wouldn't be possible to build here, since I don't have access to the steam libraries. The default is to not build with steam, and it does look like non-steam players can still play on servers, so that shouldn't pose an issue.
* Since the versions themselves are different, they might cause some server issues, such as people playing on the steam version might have issues with people using the open source version, but unsure if that will pose an issue or not. Do you know?
* Soldat itself does not have any GUI, so currently the way to join is with the command line. They do have a launcher built with electron (https://github.com/rzaba0/soldat-launcher), but unsure how far along it is. There have been issues in the past with building electron apps, as the steam runtime does not have cups, which is required to use chromium applications. There's a workaround for that, to use the much older ubuntu 12-based runtime, but that can cause its own issues. Another option might be to see if something like nwjs could load it for just the launcher piece.
* 64-bit does not appear to work very well (https://github.com/Soldat/soldat/wiki/A-beginner's-guide-to-Soldat-development#misc-1), so it'd need to be a 32 bit build.
* Would need to investigate further freepascal building: https://github.com/archlinux/svntogit-community/blob/packages/fpc/trunk/PKGBUILD

Would this be something you'd be interested in seeing about building? I could also look at it instead if you'd prefer.

**Comment by ToughGuyKunio** [comment]
>     * Since the versions themselves are different, they might cause some server issues, such as people playing on the steam version might have issues with people using the open source version, but unsure if that will pose an issue or not. Do you know?

I don't know, would need to investigate.

> Would this be something you'd be interested in seeing about building? I could also look at it instead if you'd prefer.

I feel this might be a bit out of my level for now. I have some other engines that I'm thinking about building, after I'm done with them and gathered some more experience I might be able to look into this. So we could always put this on hold for a while.

**Comment by d10sfan** [comment]
Going to close this for now, as it has issues with the steam integration, launcher, etc, along with being 32-bit only has its own issues.

Will be open to re-looking if there's additional interest.
