### ISSUE TITLE
Daggerfall Unity

### ISSUE THREAD

**Issue by holmraven** [luxtorpeda-dev/packages#664]
### Project Link

https://github.com/Interkarma/daggerfall-unity

### Project License

MIT License

### Steam App Ids

https://steamdb.info/app/1812390/

**Comment by d10sfan** [comment]
@holmraven 

Thanks for the interest. I'm already working on the engine, but it's currently on hold due to an issue with it running inside the Steam environment. Once that is fixed, I'll be able to implement it pretty quickly.

You can watch progress here: https://github.com/luxtorpeda-dev/packages/pull/651
