### ISSUE TITLE
Package Request: Sonic CD 11 Decompilation

### ISSUE THREAD

**Issue by Fancy2209** [luxtorpeda-dev/packages#678]
### Project Link

https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation

### Project License

Custom: https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/blob/master/LICENSE.md

### Steam App Ids

https://steamdb.info/app/200940/

### Additional Context

To install mods the folder scripts from [here](https://github.com/Rubberduckycooly/Sonic-CD-2011-Script-Decompilation) needs to be on the game directory.
To run the game the executable from the decompilation simply needs to be on the folder If I understood correctly.

**Comment by Fancy2209** [comment]
Since this is a won't fix I will close the issue, but mind explaining why?

**Comment by d10sfan** [comment]
@Fancy2209 

Thanks for the request. I've looked at sonic cd before, and because of the issues with re3 in the past, I prefer to avoid decompilation projects due to the unclear licensing. You can see https://github.com/luxtorpeda-dev/packages/issues/184#issuecomment-961869210 for a bit more information. You can also use user-packages if you have it installed and want an easy way to launch the game.

**Comment by Fancy2209** [comment]
> @Fancy2209
> 
> Thanks for the request. I've looked at sonic cd before, and because of the issues with re3 in the past, I prefer to avoid decompilation projects due to the unclear licensing. You can see [#184 (comment)](https://github.com/luxtorpeda-dev/packages/issues/184#issuecomment-961869210) for a bit more information. You can also use user-packages if you have it installed and want an easy way to launch the game.

Ok, thanks for the heads up
