### ISSUE TITLE
OpenMW (Latest) no crosshair & 3rd person doesn't work

### ISSUE THREAD

**Issue by witheredwojak** [luxtorpeda-dev/packages#683]
### Game

The Elder Scrolls III: Morrowind

### Engine

OpenMW (Latest)

### Linux Distribution

Linux Mint 20.3 Cinnamon

### Luxtorpeda Version

54

### Bug description

There is no crosshair and 3rd person look in game.

### Steps To Reproduce

I installed OpenMW (Latest) after playing on OpenMW Stable 0.47 version, so I have OpenMW 0.47 inside `Morrowind` dir and OpenMW 0.48 (Latest) inside `Morrowind/openmw-latest` dir. I imported my saves from `~/.local/share/openmw` to `openmw-latest/local/openmw` and my configs from `~/.config/openmw` to `openmw-latest/config/openmw`. Loaded my save and there is no crosshair and 3rd person. Also tried to delete openmw.cfg and running launcher's installation wizard again, but none of this worked. Also I received the answer in OpenMW Discord, it seems to have problems with loading `openmw-latest/share/games/openmw/resources/vfs/builtin.omwscripts` and since version 0.48 there are some changes to openmw.cfg system: https://gitlab.com/OpenMW/openmw/-/merge_requests/1555

### Expected Behavior

Crosshair and 3rd person works again.

### Relevant log output

```shell
openmw.log:
https://pastebin.com/V7WBWAWu
```

**Comment by witheredwojak** [comment]
Tried deleting all related to openmw (configs from ~./config/openmw, saves from ~./local/share/openmw, 0.47 version from Morrowind dir, etc) and fresh installing openmw-latest but still no crosshair & 3rd person

**Comment by witheredwojak** [comment]
(sorry, accidentally closed the issue)

**Comment by d10sfan** [comment]
@witheredwojak Thanks for the report, I'll take a look.

You shouldn't need to mess with the user directory saves and  config directories, as latest is trying to use a local to the directory path.

**Comment by d10sfan** [comment]
Looks like the main issue is that (like mentioned in the discord) that this line is missing from the config:

```
content=builtin.omwscripts
```

Once I add that, it seems to work as expected, if launched directly without the launcher. I asked in that discord for some assistance regarding it seems like that line is removed if you launch from the launcher.

I created this PR for the progress so far: https://github.com/luxtorpeda-dev/packages/pull/684

Once I know more, I'll update.

**Comment by witheredwojak** [comment]
> Once I add that, it seems to work as expected, if launched directly without the launcher. I asked in that discord for some assistance regarding it seems like that line is removed if you launch from the launcher.

In which openmw.cfg did you add this line? Because I already have `content=builtin.omwscripts` in global openmw.cfg (`openmw-latest/etc/openmw`) but crosshair/3rd person doesn't work. 
Also, are there any temporary ways to fix the problem? Because I'm afraid to continue my 0.47 savegame on this version. Maybe my savegame will break because of this problem? Do I need to go back to openmw 0.47?

**Comment by d10sfan** [comment]
With the recent changes they use the local one only from what I can tell, so it'd be the openmw.cfg file in the openmw-latest directory. The issue currently though is the launcher seems to remove it. If I don't get any response or figure it out soon I'll update so that the game launches directly without the launcher for now, just for latest.

**Comment by d10sfan** [comment]
@witheredwojak 

I've made these changes - https://github.com/luxtorpeda-dev/packages/commit/55993cca31bdc352b52ba82ae0c48e29cbd4cc28 that should fix the issue

The openmw.cfg and settings.cfg are expected to be in ./openmw-latest/config/openmw, provided that you start in the Morrowind game directory. I've created soft links from that directory to ./openmw/openmw.cfg, but you shouldn't need to worry about that.

Now, if that config file does not contain the builtin.omwscripts line, it will create it, so you should only have to copy your config and saves from 0.47 and it should do the rest. Changing the ./etc/openmw files won't do anything, as it'd only using the openmw.cfg provided, like mentioned previously.

These changes also remove the launcher and instead launch the game directory. This is because of the issue where the launcher removes the builtin scripts line. Once that is resolved, I'll provide a way to launch with the launcher again. I've changed the config script to add the shadows enable line to allow the new shaders to work properly, if setings.cfg does not exist

This should be live about 2 hours from this comment, once it all finishes building. Let me know if you run into any issues and how it goes when you try it again.

**Comment by witheredwojak** [comment]
Well, game doesn't start at all now. A luxtorpeda's window for choosing what to run appears, and when I select OpenMW (Latest) the game immediately stops.

**Comment by witheredwojak** [comment]
Here is steam console log:
https://pastebin.com/UakHKcuT

**Comment by d10sfan** [comment]
@witheredwojak There should be more logs after that, it looks like something is missing. I don't see any logs from luxtorpeda in there, which should normally be there.

Could you try running steam in terminal again and seeing what the output has?

Also, you can try the logging instructions at https://github.com/luxtorpeda-dev/luxtorpeda#configuration

**Comment by d10sfan** [comment]
@witheredwojak Great, good to hear!

**Comment by d10sfan** [comment]
@witheredwojak 

I've added back support for the launcher (https://github.com/luxtorpeda-dev/packages/commit/6e59574dd0c27e1946183d54d53534f0bacab02e). This changes the config structure a bit, but it should be usable without having to change anything manually. Config is in ./openmw-latest/local-cfg and soft links are created for existing files.

Let me know if you run into any issues on the new build. The existing options should act the same way, with new launcher options.

**Comment by Spaicrab** [comment]
I'm getting the exact same issue as described here.
Running the Launcher through Luxtorpeda deletes `content=builtin.omwscripts` from openmw.cfg, breaking the crosshair and 3rd person.
It works fine when running openmw without the launcher, but I needed to re-add the line in openmw.cfg manually.

**Comment by d10sfan** [comment]
@Spaicrab If you can create a new ticket for that issue, I'll take a look soon.

**Comment by Spaicrab** [comment]
Alright, I'll make a new issue as soon as I can.
