### ISSUE TITLE
OpenMW Lancher for Other builds.

### ISSUE THREAD

**Issue by GameEnder** [luxtorpeda-dev/packages#688]
### Feature Request

OpenMW Add Launcher Options for tes3mp and Nightly builds.

### Solution

Add launcher options for the other builds of OpenMW that available for use. Would be useful to configure options and mods for those builds.

**Comment by d10sfan** [comment]
@GameEnder Thanks for the issue.

openmw-tes3mp already launches using the launcher, using the "openmw-tes3mp" option for it. You use the launcher to pick your options and mods and then the server browser is launched when you click play.

The openmw latest option does not have the launcher option because from testing the line to import the lua scripts gets removed when using the launcher. I have been unable to find a fix for that and did not get any responses when asking on discord about it. If that's fixed, or if a workaround is found, I can add a launcher option.

Let me know if you need anything or have any more questions.

**Comment by d10sfan** [comment]
@GameEnder 

I've added back support for the launcher (https://github.com/luxtorpeda-dev/packages/commit/6e59574dd0c27e1946183d54d53534f0bacab02e). This changes the config structure a bit, but it should be usable without having to change anything manually. Config is in ./openmw-latest/local-cfg and soft links are created for existing files.

Let me know if you run into any issues on the new build. The existing options should act the same way, with new launcher options.
