### ISSUE TITLE
Add  R.E.L.I.V.E for Abe's Oddysee and Oddworld: Abe's Exoddus.

### ISSUE THREAD

**Issue by coreybruce** [luxtorpeda-dev/packages#737]
### Feature Request

Add  R.E.L.I.V.E to Luxorpeda as it's a open source re-implementation engine for Abe's Oddysee and Oddworld: Abe's Exoddus which does a lot of fixes for the game and also  gives a native Linux version.

### Solution

Add  R.E.L.I.V.E to Luxorpeda
https://github.com/AliveTeam/alive_reversing

**Comment by d10sfan** [comment]
I moved this to the packages repo. I try to avoid projects with unclear licensing, in this case because it's a reverse engineering project instead of building a custom implementation like most open source projects.

Because of this I won't be implementing this one but think you for the request. If you think of any other projects feel free to make a request in the packages repo.

**Comment by coreybruce** [comment]
Ahh I see so is it because of the unclear licensing or the fact it's a re-implementation? because there is a lot of great re-implementation projects that would be great to add to this project.

**Comment by d10sfan** [comment]
@coreybruce Mainly about it being a reverse engineering project, but also the fact there is not a license. Some of the reverse engineering projects provide licenses for their code, but I've seen issues with projects like that in the past. re3 is a good example.

**Comment by coreybruce** [comment]
Yeah maybe if I asked them about the licencing than maybe that answer could change?

**Comment by d10sfan** [comment]
@coreybruce for this particular project I believe it's been asked already, a bit ago

**Comment by coreybruce** [comment]
Looks like they don't have a real licence yet but I'd they did it would be MIT

**Comment by d10sfan** [comment]
@coreybruce 

Right that's one of the main issues there, this was discussed with them a while back (https://github.com/AliveTeam/alive_reversing/issues/1083).

The other issue is since it's a reverse engineering project, it's in a grey area. The other projects that I support are mainly related to re-creating the engine from scratch, or using source ports, with freely available source code. Because of experience with projects like re3, which were taken down, I am wary of those, but I appreciate the interest.

If you do have any ideas that have clear licenses and aren't reverse engineering projects, feel free to open an issue here for discussion.

**Comment by coreybruce** [comment]
Yeah that's understandable, it was sad to see them wrongfully take down and ruin re3 project
