### ISSUE TITLE
Package unofficial Entropy : Zero 2 port

### ISSUE THREAD

**Issue by z33ky** [luxtorpeda-dev/packages#759]
### Project Link

https://github.com/z33ky/source-sdk-2013/tree/ez2/mapbase
https://github.com/z33ky/source-sdk-2013/releases/tag/ez2-1.0.1.linux0

### Project License

SOURCE 1 SDK LICENSE

### Steam App Ids

1573720

### Additional Context

I am the author of the port.
I do not use Luxtorpeda but [have been asked](https://old.reddit.com/r/linux_gaming/comments/xszlva/unofficial_port_of_halflife_2_mod_entropy_zero_2/iqngkcy/) to signal availability and my blessings for packaging.

**Comment by d10sfan** [comment]
@z33ky Thanks for the port and the request! I've created a PR for that - https://github.com/luxtorpeda-dev/packages/pull/760 and I also needed to change the gameinfo.txt a little bit, since with luxtorpeda, we are launching the game directly, instead of through the source mod interface (https://github.com/luxtorpeda-dev/packages/blob/5da1bdc25afdea4a2b5842e0b9c17919672c3147/engines/source-sdk-2013/assets/entropy-zero2/gameinfo-override.txt).

It loaded as you can see below in the screenshot, although there are some sounds that are not loading correctly, and possibly there could be issues with other resources if there are case sensitivity issues.

![20221003083617_1](https://user-images.githubusercontent.com/4337981/193592097-69b46793-8ae7-4d44-b571-16862c523e79.jpg)

Are you seeing something similar with using it as a source mod? For example, the following logs show up in the console, and there isn't a sound played when you rollover the UI. As well, if you go into the game, or use the bonus map where you play as a rebel, the pistol does not make any noise.

```
Failed to load sound "p2/amb_eerie_wind_lp_01.wav", file probably missing from disk/repository
Failed to load sound "UI/buttonrollover.wav", file probably missing from disk/repository
```

For the original game (https://github.com/luxtorpeda-dev/packages/blob/master/engines/source-sdk-2013/assets/entropy-zero/run-entropy-zero.sh#L40), I ended up creating lower-case links for all of the audio, since we're dealing with case sensitivity. In this game, it looks like the sound files are in the vpks. I did look at one and it had ui/buttonrollover.wav, but all lower-case, so that possibly could be the issue, but not sure.

Here's a full log of the attempt: [run-attempt.log](https://github.com/luxtorpeda-dev/packages/files/9697939/run-attempt.log)

**Comment by rea987** [comment]
@d10sfan Not sure if related but I needed to use [ValvePython's vpk](https://github.com/ValvePython/vpk) to get all sounds for another Source engine mod, **Black Mesa: Blue Shift**.

https://www.reddit.com/r/linux_gaming/comments/rasla9/black_mesa_blue_shifts_halflife_blue_shift_remake/

**Comment by d10sfan** [comment]
@rea987 

I was mainly curious first if this happened in the mod version, to make sure it wasn't an issue with the configuration.

But assuming it's a case sensitivity issue, extracting the vpk and using that instead could be an option. I've tried the source sdk 2013 and tf2 vpk_32 binary that is included, although it isn't giving behavior I want. For source  sdk 2013 version, it seg-faults.  For tf2 version, If I ask it to extract the vpk, it creates the directory structure but the files are not there.

I haven't tried that vpk repo yet, although would need to figure out a way to package it if that works.

**Comment by rea987** [comment]
> I've tried the source sdk 2013 and tf2 vpk_32 binary that is included, although it isn't giving behavior I want. For source sdk 2013 version, it seg-faults. For tf2 version, If I ask it to extract the vpk, it creates the directory structure but the files are not there.

Yeah, vpk binary included in Valve's other Source games didn't work for me. [ValvePython's vpk](https://github.com/ValvePython/vpk) did the trick for Black Mesa: Blue Shift.

**Comment by d10sfan** [comment]
@rea987 Thanks, it looks like the valvepython one did the trick, I had to get python setuptools and this package to install locally, and then use it to extract the vpks. Whenever a new version of the game comes in, I'll have to figure out deciding when to extract again, but it looks to be working. 

I've added support with it with this commit: https://github.com/luxtorpeda-dev/packages/commit/6e906311b2a961ed31f37ccf6619a9a7c5b90932

This should work out of the box, without any manual steps required. Please feel free to help test and let me know if you run into any issues.

Also, if there's any suggestions as to better ways of handling this, feel free to comment here.

**Comment by d10sfan** [comment]
@z33ky It looks like there's a bug with the game. There's a scene where the an apc is air-dropped, when the combine drops it, it gets stuck in the air (i'm assuming it's supposed to fall down to the ground). Let me know of any other information you may need from me. 

![20221004135439_1](https://user-images.githubusercontent.com/4337981/193903401-7e4c1091-1b4d-463a-9881-90aa24341888.jpg)

**Comment by z33ky** [comment]
Yeah, that happened to me too. I was hoping this may just be an issue with my run. I will check it out on the weekend.
In the meantime you can continue on foot or with `ch_createdrivableapc`, though that may break some scripting.

About achievements, I have never cared about them, so I haven't noticed. I'll see if I notice anything, but I will probably not invest much time there.

**Comment by z33ky** [comment]
About the content, I have noticed that Source seems to behave differently for paths specified with `|all_source_engine_paths|`-prefix than other paths. Maybe it's something with using VPKs, I don't know; it was just trial and error on my side to get the sourcemods-version working. Good thing you found a workaround for your installation method.

**Comment by d10sfan** [comment]
> Yeah, that happened to me too. I was hoping this may just be an issue with my run. I will check it out on the weekend. In the meantime you can continue on foot or with `ch_createdrivableapc`, though that may break some scripting.
> 
> About achievements, I have never cared about them, so I haven't noticed. I'll see if I notice anything, but I will probably not invest much time there.

Thanks for the reply :) Please feel free to comment here  if you end up finding a fix for the apc issue. I ended up going to proton and back, although that's a good point for future use for others.
