### ISSUE TITLE
The Alternative Mod Launcher (AML) for XCOM 2 and XCOM Chimera Squad

### ISSUE THREAD

**Issue by eskoONE** [luxtorpeda-dev/packages#788]
### Project Link

https://github.com/X2CommunityCore/xcom2-launcher

### Project License

GNU General Public License v3.0

### Steam App Ids

https://steamdb.info/app/268500/ XCOM 2
https://steamdb.info/app/882100/ XCOM Chimera Squad

### Additional Context

there is a [reddit post](https://old.reddit.com/r/xcom2mods/comments/rhjeby/you_can_run_aml_on_linux_proton_howto_included/) detailing how they got it running under linux.

**Comment by d10sfan** [comment]
@eskoONE Luxtorpeda is mainly about running native games through the Steam compatibility tool interface. Because of that, there isn't an easy way to trigger proton to run as part of luxtorpeda currently.

It looks like this would entail running a game through Proton after extracting some tools, which is outside the scope of luxtorpeda at the moment.

If there ends up being other games or reasons that could benefit from this, I could look into it again.
