### ISSUE TITLE
Lode Runner: Mad Monk's Revenge

### ISSUE THREAD

**Issue by sybenx** [luxtorpeda-dev/packages#819]
### Project Link

https://mmr.quarkrobot.com/

### Project License

closed-source, free

### Steam App Ids

https://store.steampowered.com/app/628660/Lode_Runner_Legacy

### Additional Context

There's no direct equivalent on Steam for Lode Runner: Mad Monk's Revenge Definitive Edition on Steam but Lode Runner Legacy is of the same series. Lode Runner: Mad Monk's Revenge Definitive Edition is entirely standalone. The original game is available on [myabandonware](https://www.myabandonware.com/game/lode-runner-on-line-the-mad-monks-revenge-3m6).

**Comment by d10sfan** [comment]
@sybenx Thanks for the request, i'll look into it and get back to you when I have a chance

**Comment by d10sfan** [comment]
@sybenx Is there a way to play the content of the steam game with this standalone game? Mainly wondering due to seeing if these really apply to each other, since usually luxtorpeda games are supposed to be able to play the content of the steam game, not play a different game altogether.

**Comment by sybenx** [comment]
This is a standalone game.

**Comment by d10sfan** [comment]
@sybenx Thanks for the issue, but since this game doesn't really apply to the steam game (as in you can't play the content for example), it does not really match with the end goals of the project.

If you'd like you can use the user-packages feature (https://github.com/luxtorpeda-dev/luxtorpeda#user-packages-override) to play the game yourself.
