### ISSUE TITLE
RuneScape Download URL Changed

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#864]
### Game

https://store.steampowered.com/app/1343400/RuneScape/

### Engine

RuneScape (Proprietary)

### Linux Distribution

NixOS/Flatpak

### Luxtorpeda Version

62

### Bug description

Currently running a fresh Runescape with Luxtorpeda results in the game not launching. I discovered a corrupted .deb file so extraction of game data was not possible. 

A quick `file` on the deb

```
> file runescape-launcher_2.2.10_amd64.deb 
runescape-launcher_2.2.10_amd64.deb: HTML document, ASCII text, with very long lines (726)
```

Going to the download URL, nothing happens. It's just a blank HTML page. I then try incrementing the version by one, success download starts.

Renaming the download and replacing the deb in the cache results in a successful game launch.

In short,

`https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.10_amd64.deb`
should be changed to
`https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.11_amd64.deb`

### Steps To Reproduce

Run Runescape with Luxtorpeda without any cache of existing launcher files.
The game fails to start.

### Expected Behavior

Luxtorpeda should download, extract, and run the game.

### Additional Context

Is there any way we can automatically use the latest version or at least create a friendly dialog to the user so they can report the problem and the version can be manually incremented? It seems pretty rare that an update occurs to the Runescape launcher itself.

### Relevant log output

```shell
16:47:41 [INFO] copying: runescape-launcher_2.2.10_amd64.deb
16:47:41 [INFO] installing: runescape-1343400-3
16:47:41 [INFO] install: "run-runescape.sh"
16:47:41 [INFO] install: "7z"
16:47:41 [INFO] install: "7z/7z"
16:47:41 [INFO] install: "7z/Codecs"
16:47:41 [INFO] install: "7z/Codecs/Rar.so"
16:47:41 [INFO] install: "7z/7zr"
16:47:41 [INFO] install: "7z/7za"
16:47:41 [INFO] install: "7z/7z.so"
16:47:41 [INFO] install: "7z/7zCon.sfx"
16:47:41 [INFO] install: "license"
16:47:41 [INFO] install: "license/yasm.COPYING"
16:47:41 [INFO] install: "license/LICENSE.runescape"
16:47:41 [INFO] install: "license/DOC.unRarLicense.txt"
16:47:41 [INFO] run: "./run-runescape.sh" with args: [] []
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
./run-runescape.sh: line 9: ./usr/share/games/runescape-launcher/runescape: No such file or directory
pid 1717 != 1716, skipping destruction (fork without exec?)
16:47:41 [INFO] run returned with exit status: 127
```

**Comment by d10sfan** [comment]
Thanks for the issue, I fixed this in https://github.com/luxtorpeda-dev/packages/commit/d9e29292ccbc51581f83ece9d4738c3c20764e67

so that it should have the new version. Let me know if you run into any issues.

I don't see a way to have a "latest", that'd depend on their server to provide that.

These sort of things could benefit from an error dialog at the end for non-lux caused errors. The launch scripts can trigger error codes, which then allow the client to show an error to the user. For other error codes (anything the app sends back that isn't a 0), those are ignored currently.

I could add a new feature to the client to trigger the UI to show an error popup with anything but a 0 comes in, and let the user generate a bug report, either send them to a link to github or use their api (https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue). The API could make it easier for people on the steam deck, since I'm not sure opening a browser window would work properly, although it may be harder to trace it to a person to re-test if needed. We could provide them with the issue number so they can manually post something later.

Another option could be to instead of automatically closing the window (it currently stays open in the background saying "running"), keep it open and let them report a bug there. That could be a bit annoying to have to close it each time though.

Curious to see your thoughts.

**Comment by JoshuaFern** [comment]
So when it downloads the old file you get a `.deb` but it's actually a HTML document, you can check for this by running `file` as I did and looking for the text `HTML document` or similar - then run whatever logic you want.

I'm not super familiar with all of Github's tools, but it seems there must be a way you could bypass the entire user report and have a bot do an automated check sometimes to make sure the URL is still valid and automatically create an issue if it's not.

Because I personally know people who have used Runescape on Luxtorpeda and if it doesn't launch they don't start Steam in a terminal, get the log, diagnose the problem and create an issue on Github. Instead they just use Proton.

**Comment by d10sfan** [comment]
That's true, I have been interested in an idea of checking for new releases and the like, as what I do know is basically get release emails from github, but for stuff on gitlab or others (where they tag so it's something I can look for), a cron job could be helpful to check all the repos.

And this check could be done the same way, to create an issue if it turns out the downloaded file is an HTML document. 

Github actions has the "schedule" option (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), so that could be used, mainly daily, and if something goes wrong, it can create an issue from there.

**Comment by d10sfan** [comment]
I created a feature issue to track that: https://github.com/luxtorpeda-dev/packages/issues/865

This should be flexible for any future work that could be useful in this area.
