### ISSUE TITLE
Xash3D FWGS engine

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#88]
From https://github.com/dreamer/luxtorpeda/issues/67

* Project link: https://github.com/FWGS/xash3d-fwgs
* Project license: Unknown, marking as non-free - https://github.com/FWGS/xash3d-fwgs/issues/63
* Does it work on 64-bit only Linux: NO, 32-bit required
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://store.steampowered.com/app/812440/HalfLife_Absolute_Zero/
    - https://store.steampowered.com/app/70/HalfLife/
    - https://store.steampowered.com/app/40/Deathmatch_Classic/
    - https://store.steampowered.com/app/50/HalfLife_Opposing_Force/
    - https://store.steampowered.com/app/60/Ricochet/
    - https://store.steampowered.com/app/130/HalfLife_Blue_Shift/
    - https://store.steampowered.com/app/20/Team_Fortress_Classic/

## Additional information

Need to determine if all games listed above are supported.

Absolute Zero information here: https://www.reddit.com/r/linux_gaming/comments/htc25t/halflife_absolute_zero_can_run_natively_on_linux/

https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/supported-mod-list.md

https://www.moddb.com/engines/xash3d-fwgs-engine

**Comment by nekonomicon** [comment]
This information is completely wrong.
Our project was named as `Xash3D FWGS` when Xash3D was developed by another man.

>Does it work on 64-bit only Linux: NO, 32-bit required

Nope. You can compile 64-bit libraries.

>https://store.steampowered.com/app/10/CounterStrike/
>https://store.steampowered.com/app/80/CounterStrike_Condition_Zero/
>https://store.steampowered.com/app/30/Day_of_Defeat/

All this games does not work under Xash3D and Xash3D FWGS.

>Absolute Zero information here: https://www.reddit.com/r/linux_gaming/comments/htc25t/halflife_absolute_zero_can_run_natively_on_linux/

I think this mod not fully work under Xash3D FWGS on linux.

>https://www.indiedb.com/engines/xash3d-engine/features/running-half-life-under-xash3d-users-manual-english

This manual for original Xash3D, so it's completely bad idea to use this manual for Xash3D FWGS.

>https://www.moddb.com/engines/xash3d-engine/tutorials/xash3d-compatible-half-life-mods-for-any-supported-os

It would be better to check this list:
https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/supported-mod-list.md

Also, we have separate page on moddb:
https://www.moddb.com/engines/xash3d-fwgs-engine

**Comment by d10sfan** [comment]
Ok, thanks for the information. This was mainly following the links on the README.md in the repo, which links to the other project's moddb page

Is the description here no longer valid? This is where I got the idea that it'd only be 32-bit: https://github.com/FWGS/xash3d-fwgs#gnulinux

Is there a list of steam games that work with Xash3D FWGS?

**Comment by a1batross** [comment]
While we do support 64-bit and successfully utilize it in different ports, the only thing that stops us using 64-bit on GNU/Linux and Windows is binary compatibility.

GoldSource engine doesn't have any kind of virtual machine like Quake, although being derived from it. So to load a Half-Life mod on a Linux, you need to find source code of game logic DLLs and recompile them to Linux. @nekonomicon is working on that field, fixing different mods or reverse engineering them to be compatible with most platforms we support: https://github.com/FWGS/hlsdk-xash3d

Other our precious contributor @mittorn had implemented DLL loader support for the old engine branch. Support was limited to old mods that was built with old Visual Studio compilers, so it's would not be compatible with newer ones.
It's **NOT** ported for new engine and it's future is not bright. I don't like how it's being injected to the engine instead of being a wrapper, like QuakeWrapper, a QuakeC virtual machine implemented as Half-Life mod. Also, I don't like it's source code, it's hard to read and probably contains a lot of errors we've never encountered due to obscurity of this feature. :(

**Comment by nekonomicon** [comment]
>Is there a list of steam games that work with Xash3D FWGS?
CS 1.6, CS: CZ and DOD uses vgui2 library which Xash3D does not support at all.

CS: CZ-DS required special sequence support on engine side that was implemented in Xash3D FWGS by @a1batross, but without vgui2 support It does not work too.

Other games must work fine.

Also, many Half-Life-based games and mods required vgui1 library as dependency, but this library is closedsource and exists only for 32-bit x86 architecture, and for porting to other platforms need to remove vgui interface from client library.

**Comment by a1batross** [comment]
@nekonomicon Nagist's vgui is opensource and under permissive license. But it's never tested.

**Comment by thaewrapt** [comment]
As a starter of this topic (kinda) I'd like to clarify something.

> > Absolute Zero information here: https://www.reddit.com/r/linux_gaming/comments/htc25t/halflife_absolute_zero_can_run_natively_on_linux/
 
> I think this mod not fully work under Xash3D FWGS on linux.

Have you checked the instructions by the link? They report it working with version 0.19 (and not working with version 0.20) of Xash3D FWGS — and this task need some workarounds, if I got that correctly. It's very interesting to get your detailed commentaries as the creators of the engine, and what could be done (and what, most probably, not).

**Comment by nekonomicon** [comment]
@thaewrapt @a1batross already said about dll-loader.

Dll-loader is kludge which based on an old version of wine and with normal half-life client some features will not work, such as dynamic fog, so there is no way to run this mod on linux natively.

But HL: Absolute Zero is opensource and It's possible to port this mod to linux.

https://gitlab.com/Cobalt-57/half-life-absolute-zero/

**Comment by thaewrapt** [comment]
@nekonomicon Thanks for clarification, I'm still being confused by the way those people from Reddit thread have used game_ui.so and particleman.so from a current Steam version of Half-Life to make AZ work with your engine, I'll try their solution to check if it's actually working, haven't got any spare time yet.

As for devs of Absolute Zero, they seem unaware of possibility to make a native Linux port due to (quote) "older version of GoldSrc being used and not available for Linux".

**Comment by nekonomicon** [comment]
>particleman.so

It's particle manager library that used only in CS 1.6 and DOD.

>game_ui.so

It's vgui2-based steam menu user interface, but Xash3D does not support it and uses own UI library.

>As for devs of Absolute Zero, they seem unaware of possibility to make a native Linux port due to (quote) "older version of GoldSrc being used and not available for Linux".

Main difference in old and new HLSDK - input device code:
https://gitlab.com/Cobalt-57/half-life-absolute-zero/-/blob/master/cl_dll/inputw32.cpp
https://github.com/ValveSoftware/halflife/blob/master/cl_dll/inputw32.cpp

Valve just ported old input code from win32 api to sdl2.
Also, may be need to fix old code for modern C/C++ compilers, but it's not hard.

We have guide about mod porting, but this guide is more related to Xash3D:
https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/mod-porting-guide.md

**Comment by d10sfan** [comment]
Absolute Zero is getting delisted from Steam soon - https://store.steampowered.com/newshub/app/812440/view/2916602385067012696

Closing for now, unless there's interest and/or anyone wants to try to provide a PR for supporting this engine.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/233
