### ISSUE TITLE
Add DREAMM for multiple games

### ISSUE THREAD

**Issue by Jpxe** [luxtorpeda-dev/packages#982]
### Project Link

https://aarongiles.com/dreamm/

### Project License

Proprietary

### Steam App Ids

- https://store.steampowered.com/app/456540/
- https://store.steampowered.com/app/354430/
- https://store.steampowered.com/app/355250/
- https://store.steampowered.com/app/32400/
- https://store.steampowered.com/app/560170/
- https://store.steampowered.com/app/32380/
- https://store.steampowered.com/app/32390/
- https://store.steampowered.com/app/904540/
- https://store.steampowered.com/app/557240/
- https://store.steampowered.com/app/559620/
- https://store.steampowered.com/app/730830/

### Additional Context

Also includes all the SCUMM gamess but I didn't include them here since there's already ScummVM for that, see here for more: https://aarongiles.com/dreamm/docs/v21/#intro-games

Installation instructions are here: https://aarongiles.com/dreamm/docs/v21/#install-install-linux

I haven't tried it myself yet so I'm not sure which Steam games work yet. Some might be missing required files. If there's interest in implementing this engine let me know and I check it out.

**Comment by d10sfan** [comment]
I should be able to add it as a default engine, so it could be picked for multiple games, similar to scummvm. I'll take a look when I have a chance.

Would also appreciate any help you can give in terms of testing games if you'd like

**Comment by d10sfan** [comment]
I've added it in recent commits. Note that some steam games may not work because of https://aarongiles.com/dreamm/docs/v21/#adding-missing

So I'm not sure how much utility we'll get out of it, but please feel free to test and see if there's some games that work with it. If so, we could add them as direct users of dreamm in the metadata.

Note that you'll need the latest client for this to work (will be done when this action is complete - https://github.com/luxtorpeda-dev/luxtorpeda/actions/runs/6086133951), as the file extension was tgz which wasn't being detected as a tar.gz file (same thing with a different extension).
